dist: trusty
language: rust

rust:
#  - stable
  - nightly

sudo: true

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5

install:
  - sudo apt-get install -y libsnappy-dev zlib1g-dev libbz2-dev
  - curl -L https://github.com/facebook/rocksdb/archive/4.13.fb.tar.gz | tar xvz
  - make -C rocksdb-4.13.fb shared_lib

env:
  - LD_LIBRARY_PATH=$PWD/rocksdb-4.13.fb

script:
  - cargo test --manifest-path=kite/Cargo.toml
  - cargo test --manifest-path=kite_rocksdb/Cargo.toml
  - cargo test
