language: rust

rust:
  - stable
  - nightly

dist: trusty
sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libgflags-dev
    - libsnappy-dev
    - zlib1g-dev
    - libbz2-dev

install:
  - curl -L https://github.com/facebook/rocksdb/archive/4.13.fb.tar.gz | tar xvz
  - sudo INSTALL_PATH=/usr make -C rocksdb-4.13.fb install-shared

script:
  - cargo test --manifest-path=kite/Cargo.toml
  - cargo test --manifest-path=kite_rocksdb/Cargo.toml
  - cargo test
