[package]
name = "rusticsearch"
version = "0.1.0"
authors = ["Karl Hobley <karlhobley10@gmail.com>"]
license = "Apache-2.0"

[dependencies]
iron = "0.4.0"
router = "0.2.0"
persistent = "0.2.0"
url = "*"
rustc-serialize = "0.3"
log = "*"
unicode-segmentation = "*"
maplit = "*"
chrono = "0.2"
roaring = "0.4.0"
byteorder = "0.5"
slog = "0.6"
slog-term = "0.6"

[dependencies.kite]
path = "kite"
version = "0.0.1"

[dependencies.kite_rocksdb]
path = "kite_rocksdb"
version = "0.0.1"
