[package]
name = "rusticsearch"
version = "0.1.0"
authors = ["Karl Hobley <karlhobley10@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
persistent = "*"
url = "*"
rustc-serialize = "0.3"
log = "*"
unidecode = "*"
unicode-segmentation = "*"
maplit = "*"
